// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using HDR_UK_Web_Application.Models;
//
//    var observationModel = ObservationModel.FromJson(jsonString);

using Newtonsoft.Json.Serialization;

namespace HDR_UK_Web_Application.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ObservationModel
    {
        [JsonProperty("resourceType")]
        public string ResourceType { get; set; }

        [JsonProperty("id")]
        public Guid Id { get; set; }

        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("category")]
        public Category[] Category { get; set; }

        [JsonProperty("code")]
        public Code Code { get; set; }

        [JsonProperty("subject")]
        public Encounter Subject { get; set; }

        [JsonProperty("encounter")]
        public Encounter Encounter { get; set; }

        [JsonProperty("effectiveDateTime")]
        public DateTimeOffset EffectiveDateTime { get; set; }

        [JsonProperty("issued")]
        public DateTimeOffset Issued { get; set; }

        [JsonProperty("valueQuantity")]
        public ValueClass valueQuantity { get; set; }
        
        [JsonProperty("valueBoolean")]
        public ValueClass valueBoolean { get; set;}
        
        [JsonProperty("valueString")]
        public ValueClass valueString { get; set;}
        
        [JsonProperty("valueInteger")]
        public ValueClass valueInteger { get; set;}
        
        [JsonProperty("valueRange")]
        public ValueClass valueRange { get; set;}
        
        [JsonProperty("component")]
        public valueComponent[] Component { get; set; }
        
        [JsonProperty("valueCodeableConcept")]
        public valueCodeableConcept valueCodeableConcept { get; set;}
    }

    public partial class valueCodeableConcept
    {
        [JsonProperty("text")]
        public string value { get; set;}
    }

    public partial class valueComponent
    {
        [JsonProperty("valueQuantity")]
        public ValueClass valueQuantity { get; set;}
        
        [JsonProperty("valueBoolean")]
        public ValueClass valueBoolean { get; set;}
        
        [JsonProperty("valueString")]
        public ValueClass valueString { get; set;}
        
        [JsonProperty("valueInteger")]
        public ValueClass valueInteger { get; set;}
        
        [JsonProperty("valueRange")]
        public ValueClass valueRange { get; set;}
        
    }
    
    public partial class Category
    {
        [JsonProperty("coding")]
        public Coding[] Coding { get; set; }
    }

    public partial class Code
    {
        [JsonProperty("coding")]
        public Coding[] Coding { get; set; }

        [JsonProperty("text")]
        public string Text { get; set; }
    }

    public partial class Encounter
    {
        [JsonProperty("reference")]
        public string Reference { get; set; }
    }

    public class ValueClass
    {
        [JsonProperty("value")]
        public double Value { get; set; }

        [JsonProperty("unit")]
        public string Unit { get; set; }

        [JsonProperty("system")]
        public Uri System { get; set; }

        [JsonProperty("code")]
        public string Code { get; set; }
    }


    public partial class ObservationModel
    {
        public static ObservationModel FromJson(string json) => JsonConvert.DeserializeObject<ObservationModel>(json, HDR_UK_Web_Application.Models.Converter.Settings);
    }
}
